### ISSUE TITLE
Max authorized networks limit for the account is reached with CI nodes

### ISSUE THREAD

**Issue by orensbruli** [zerotier/github-action#10]
The max `authorized networks` limit for the account is reached with CI nodes because the post action is not authorised to delete and does not fail the workflow either.
```
⏁  Installing ZeroTier
⏁  Authorizing Runner to ZeroTier network ...
200 join OK
200 listnetworks *** ...

...

Post job cleanup.
⏁  Removing Runner from ZeroTier network
{"type":"internal","message":"Unauthorized"}
```
I can join with the token, but it looks like I don't have permission to delete.

- How can we fix the `Unauthorized` response?
- Can the account owner give this permission to me?
- and then, should I re-create the token?

I would suggest adding some checks in the initialization of the action to see that the current user/network/token combination can complete the join and delete requests or fail if not. This would avoid filling the account with authorized runners in the network.

**Comment by laduke** [comment]
Each network has it's own permissions. "Delete" is one of the permissions. The network owner can give you that permission. You shouldn't need to make a new token for that account. 

I'm not sure what to do about the error, or the cluttering of hte networks. Maybe the script should give the member a name that's easy to search and delete later.

**Comment by orensbruli** [comment]
Thank you @laduke 
To see the action failing when the member can not be deleted would be an improvement.
I have suggested a change for that but I'm not sure if an action can be failed in the "post" section.
https://github.com/zerotier/github-action/pull/11/files

What you suggest about giving a name to the members created in the CI would be a nice thing also, because it has not been obvious how to find the members I should delete after this has happened.

Also, does Zerotier API have any call that we could use to pre-check if it would fail when trying to delete a member?

**Comment by orensbruli** [comment]
Closing with #12
